version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: sample_app:v1
    restart: unless-stopped
    #env_file: .env
    environment:
      - NODE_ENV=test
  proxy:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      image: nginx_proxy:v1
      ports:
        - 8082:80
      depends_on:
        - nodejs
      deploy:
        placement:
          constraints: [node.role == manager]
